---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  HF_HOME: {{ .Values.configuration.modelStorage.rootDir }}
  HOME: {{ .Values.configuration.modelStorage.rootDir }}
  {{- if .Values.configuration.hfModelDownload.enabled }}
  HF_HUB_OFFLINE: "0"
  {{- else }}
  HF_HUB_OFFLINE: "1"
  {{- end }}
  {{- range $k, $v := .Values.configuration.env }}
  {{- if ne $k "HF_HUB_OFFLINE" }}
  {{ $k }}: {{ quote $v }}
  {{- end }}
  {{- end }}
