{{- if eq .Values.configuration.modelStorage.type "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.fullname" . }}-storage
  {{- with .Values.configuration.modelStorage.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.configuration.modelStorage.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.configuration.modelStorage.pvc.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.configuration.modelStorage.size }}
{{- end }}
