apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-mcp-server
  labels:
    app: slack-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-mcp-server
  template:
    metadata:
      labels:
        app: slack-mcp-server
    spec:
      containers:
      - name: slack-mcp-server
        image: quay.io/redhat-et/slack-mcp-server:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          npx -y supergateway --stdio "node dist/index.js" --port 8080
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: slack-bot-token
        - name: SLACK_TEAM_ID
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: slack-team-id
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
